#! /bin/sh

# Start sxhkd if not started already.
pgrep -x sxhkd > /dev/null || sxhkd &

# Start polybar
polybar top &

bspc monitor -d 1 2 3 4 5

bspc config normal_border_color "#3b4252"
bspc config focused_border_color "#5e81ac"

bspc config border_width 4
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config focus_follows_pointer true
